// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYuz_2Xvo5IIaXKePcbt-P34b0_7VLHks',
    appId: '1:816082919785:web:2f175ae5b581ffbd255df8',
    messagingSenderId: '816082919785',
    projectId: 'login-ui-283d2',
    authDomain: 'login-ui-283d2.firebaseapp.com',
    storageBucket: 'login-ui-283d2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGwI6Y1WjoauryBobje6STKoHJRZ612bM',
    appId: '1:816082919785:android:06943472e8b69dff255df8',
    messagingSenderId: '816082919785',
    projectId: 'login-ui-283d2',
    storageBucket: 'login-ui-283d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzNE4GvDjHkdqU_iI5t_t3xGWpIf6EI5M',
    appId: '1:816082919785:ios:5c8e21cf476275a1255df8',
    messagingSenderId: '816082919785',
    projectId: 'login-ui-283d2',
    storageBucket: 'login-ui-283d2.appspot.com',
    iosClientId: '816082919785-s6b5q4ooro6n293u2t46g9tn7bcfchsu.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzNE4GvDjHkdqU_iI5t_t3xGWpIf6EI5M',
    appId: '1:816082919785:ios:26c3cae1ed3db008255df8',
    messagingSenderId: '816082919785',
    projectId: 'login-ui-283d2',
    storageBucket: 'login-ui-283d2.appspot.com',
    iosClientId: '816082919785-k6276ipuluosau3qfa6fn3hnj0r2f69d.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginUi.RunnerTests',
  );
}
